markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: JeffreyJu
author: "JeffreyJu"
email: zhujunf@hotmail.com
name: "Jeffrey's Blog"
baseurl: /
url: https://jeffreyju.github.io
domain: https://jeffreyju.github.io

all_categories: [
  ["streammedia", "音视频开发","/streammedia/index.html"], 
  ["iot", "物联网", "/iot/index.html"],
  ["code", "编程语言","/codelanguage/index.html"], 
  ["linux", "Linux相关","/linux/index.html"],
  ["ai", "人工智能","/ai/index.html"],
  ["arch", "架构","/architecture/index.html"],
  ["codelife", "程序人生","/codelife/index.html"],
  ["dm", "研发管理","/devmanager/index.html"], 
  ["read", "书摘","/read/index.html"], 
  ["about", "关于","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai
